spring.application.name=calorias

# Configuracao basica do Spring
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM565919
spring.datasource.password=290103

# Configuracao para o Oracle Database
# Criar a tabela de controle de migracao no banco de dados
spring.flyway.baselineOnMigrate=true

# Mostrar as instrucoes SQL executadas no banco de dados
spring.jpa.show-sql=true

# Quebrar a exibicao da instrucao SQL em varias linhas
spring.jpa.properties.hibernate.format_sql=true
